### ISSUE TITLE
Issue for testing

### ISSUE THREAD

**Issue by ageorgou** [ageorgou/public-test-gha#1]
This issue will be used for tracking automated changes in another repository.

Some text is here

Some more text

**Comment by ageorgou** [comment]
- [ ] Give correct permissions PR ([#4](https://github.com/UCL/private-test-gha/pull/4))
- [ ] Give correct permissions PR ([#4](https://github.com/UCL/private-test-gha/pull/4))
- [ ] Try to fix so it edits instead of creating new ([#5](https://github.com/UCL/private-test-gha/pull/5))
- [ ] Don't repeat previous text ([#6](https://github.com/UCL/private-test-gha/pull/6))
